ALTER TABLE "FsboLead" ADD COLUMN IF NOT EXISTS "islemTipi" TEXT;
ALTER TABLE "FsboLead" ADD COLUMN IF NOT EXISTS "kategori" TEXT;
ALTER TABLE "FsboLead" ADD COLUMN IF NOT EXISTS "listingNo" TEXT;
ALTER TABLE "FsboLead" ADD COLUMN IF NOT EXISTS "description" TEXT;
ALTER TABLE "FsboLead" ADD COLUMN IF NOT EXISTS "images" JSONB;
ALTER TABLE "FsboLead" ADD COLUMN IF NOT EXISTS "specs" JSONB;
